### ISSUE TITLE
cookie的疑问

### ISSUE THREAD

**Issue by Randomless** [LyleMi/ucas#1]
请问学长，非校园网环境用cookie登录为何不再需要验证码captcha呢?
使用cookie后服务器对非校园网用户不再要求验证码了么?还是说cookie模拟了校园网用户？

**Comment by LyleMi** [comment]
cookie保存了登陆的状态，验证码是登陆的时候才需要的，所以使用cookie可以直接进行选课。

需要注意的是cookie有失效机制，脚本在运行的情况下，访问选课网可能会导致cookie失效，需要重新登陆。
