### ISSUE TITLE
Can't enroll course even when NOT FULL

### ISSUE THREAD

**Issue by ZeroLi-Bio** [LyleMi/ucas#11]
Hi, I tested the script to enroll course which is not full or conflicting with others schedule, however it doesn't work and returned "full" signal.

**Comment by LyleMi** [comment]
Hello, 感谢你的反馈。由于选课系统可能会进行API的变动，而且只有当期选课的账号可以进入，我没有办法进行任何的调试操作，后续的功能更新和Bug修复都是由其他同学完成的。

如果你有兴趣的话可以根据当前的网站交互更新代码并提交PR，或者可以提交详细的网络请求记录，我会尝试根据前后的网络请求记录进行修复。

**Comment by ZeroLi-Bio** [comment]
Hi，我不懂网站交互和代码，请教一下如何获取网络请求记录？

best

**Comment by Yangjiaxi** [comment]
API没有改动，post表单中多了一项 `_csrftoken` ，这个可以在HTML中拿到，此外需要在 post 的 header 中加入字段 `Referer`

方法 `enrollCourse` 这样改即可

```python
    def enrollCourse(self, cid, college):
        r = self.get(Course.selection)
        depRe = re.compile(r'<label for="id_([0-9]{3})">(.*)<\/label>')
        deptIds = depRe.findall(r.text)
        collegeName = college if college else CollegeCode[cid[:4]]
        for dep in deptIds:
            if collegeName in dep[1]:
                deptid = dep[0]
                break
        identity = r.text.split('action="/courseManage/selectCourse?s=')[1].split('"')[0]
        data = {"deptIds": deptid, "sb": 0}
        categoryUrl = Course.category + identity
        r = self.post(categoryUrl, data=data)

        codeRe = re.compile(r'<span id="courseCode_([A-F0-9]{16})">' + cid + "<\/span>")
        temp = codeRe.findall(r.text)
        if temp:
            code = temp[0]

            csrf_re = re.compile(r'name="_csrftoken" value="(.*)"')  # <---
            csrf_token = csrf_re.findall(r.text)[0]  # <---
            data = {
                "_csrftoken": csrf_token,  # <---
                "deptIds": deptid,
                "sids": code,
            }
            courseSaveUrl = Course.save + identity

            self.s.headers["Referer"] = categoryUrl  # <---
            r = self.post(courseSaveUrl, data=data)
            del self.s.headers["Referer"]  # <---

            if 'class="error"></label>' in r.text:
                return None
            else:
                return "full"
        else:
            return "not found"
```

**Comment by ZeroLi-Bio** [comment]
> API没有改动，post表单中多了一项 `_csrftoken` ，这个可以在HTML中拿到，此外需要在 post 的 header 中加入字段 `Referer`
> 
> 方法 `enrollCourse` 这样改即可
> 
> ```python
>     def enrollCourse(self, cid, college):
>         r = self.get(Course.selection)
>         depRe = re.compile(r'<label for="id_([0-9]{3})">(.*)<\/label>')
>         deptIds = depRe.findall(r.text)
>         collegeName = college if college else CollegeCode[cid[:4]]
>         for dep in deptIds:
>             if collegeName in dep[1]:
>                 deptid = dep[0]
>                 break
>         identity = r.text.split('action="/courseManage/selectCourse?s=')[1].split('"')[0]
>         data = {"deptIds": deptid, "sb": 0}
>         categoryUrl = Course.category + identity
>         r = self.post(categoryUrl, data=data)
> 
>         codeRe = re.compile(r'<span id="courseCode_([A-F0-9]{16})">' + cid + "<\/span>")
>         temp = codeRe.findall(r.text)
>         if temp:
>             code = temp[0]
> 
>             csrf_re = re.compile(r'name="_csrftoken" value="(.*)"')  # <---
>             csrf_token = csrf_re.findall(r.text)[0]  # <---
>             data = {
>                 "_csrftoken": csrf_token,  # <---
>                 "deptIds": deptid,
>                 "sids": code,
>             }
>             courseSaveUrl = Course.save + identity
> 
>             self.s.headers["Referer"] = categoryUrl  # <---
>             r = self.post(courseSaveUrl, data=data)
>             del self.s.headers["Referer"]  # <---
> 
>             if 'class="error"></label>' in r.text:
>                 return None
>             else:
>                 return "full"
>         else:
>             return "not found"
> ```

谢谢，这样可以了

**Comment by LyleMi** [comment]
已对应更新，感谢
