### ISSUE TITLE
Did CollegeCode ID need to change?

### ISSUE THREAD

**Issue by xjrelc** [LyleMi/ucas#2]
F12 选课界面各学院按钮对应如下

div class="span2"
input type="checkbox" name="deptIds" id="id_957" value="957"
 label for="id_957" >天文学院</label
/div
label for="id_910"数学学院/label
...
label for="id_911"物理学院/label
 ...
 label for="id_912"化学学院/label
 ...

特在抢课开始之前想请教一下请问CollegeCode ID对应的是什么元素？
第一次选课，还没摸清选课流程，望解惑，谢谢！

**Comment by LyleMi** [comment]
CollegeCode 为学院编码 不对应网页元素 具体可查看代码

**Comment by xjrelc** [comment]
今年课程编号改了gg,QAQ
045200MGX002H-01 体育 而不是往年的TYMGX002H
马克思和人文课程编号01..
总之还是谢谢前辈分享！我自己再琢磨琢磨




------------------ 原始邮件 ------------------
发件人: "Lyle"<notifications@github.com>;
发送时间: 2019年8月29日(星期四) 上午10:13
收件人: "LyleMi/ucas"<ucas@noreply.github.com>;
抄送: "倚天〓逍遥"<524737474@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [LyleMi/ucas] Did CollegeCode ID need to change? (#2)




CollegeCode 为学院编码 不对应网页元素 具体可查看代码
